/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#000000",
        "on-secondary-fixed": "#002113",
        "tertiary": "#000000",
        "on-secondary-container": "#00714d",
        "tertiary-container": "#20005f",
        "on-secondary-fixed-variant": "#005236",
        "primary-container": "#0d1841",
        "on-surface": "#101a35",
        "surface-variant": "#dae1ff",
        "on-surface-variant": "#45464e",
        "inverse-surface": "#262f4b",
        "error": "#ba1a1a",
        "surface-container": "#eaedff",
        "on-secondary": "#ffffff",
        "surface-dim": "#cfd9fd",
        "surface-container-high": "#e2e7ff",
        "background": "#faf8ff",
        "on-background": "#101a35",
        "on-tertiary-fixed-variant": "#4f00d0",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#525c88",
        "primary-fixed-dim": "#bac4f7",
        "secondary": "#006c49",
        "inverse-on-surface": "#eef0ff",
        "on-tertiary-container": "#8d69ff",
        "secondary-container": "#6cf8bb",
        "surface": "#faf8ff",
        "inverse-primary": "#bac4f7",
        "surface-container-low": "#f2f3ff",
        "surface-bright": "#faf8ff",
        "outline": "#76767f",
        "outline-variant": "#c6c5d0",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#dde1ff",
        "on-primary-container": "#7881b0",
        "surface-container-highest": "#dae1ff",
        "on-primary-fixed": "#0d1841",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#3b446f",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#cdbdff",
        "secondary-fixed-dim": "#4edea3",
        "secondary-fixed": "#6ffbbe",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#e8deff",
        "on-tertiary-fixed": "#20005f",
        "whatsapp": "#25D366",
        "whatsapp-dark": "#128C7E",
        "whatsapp-teal": "#075E54"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "full": "9999px"
      },
      spacing: {
        "space-md": "0.75rem",
        "space-lg": "1rem",
        "space-xl": "1.5rem",
        "margin": "1.5rem",
        "gutter": "1rem",
        "space-sm": "0.5rem",
        "space-xs": "0.25rem"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"]
      },
      fontSize: {
        "label-md": ["0.75rem", { lineHeight: "1rem", fontWeight: "500" }],
        "label-lg": ["0.875rem", { lineHeight: "1.25rem", fontWeight: "600" }],
        "display-lg": ["2rem", { lineHeight: "2.5rem", fontWeight: "700" }],
        "body-sm": ["0.75rem", { lineHeight: "1rem", fontWeight: "400" }],
        "body-md": ["0.875rem", { lineHeight: "1.25rem", fontWeight: "400" }],
        "headline-sm": ["1.125rem", { lineHeight: "1.5rem", fontWeight: "600" }],
        "display-lg-mobile": ["1.75rem", { lineHeight: "2.25rem", fontWeight: "700" }],
        "body-lg": ["1rem", { lineHeight: "1.5rem", fontWeight: "400" }],
        "headline-md": ["1.25rem", { lineHeight: "1.75rem", fontWeight: "600" }],
        "label-sm": ["0.6875rem", { lineHeight: "0.875rem", fontWeight: "600" }],
        "headline-lg": ["1.5rem", { lineHeight: "2rem", fontWeight: "600" }]
      }
    }
  },
  plugins: []
}
